name: macOS Build

on:
  workflow_dispatch: ~

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: '==3.1.*'
        version: '6.2.3'
        host: 'mac'
        target: 'desktop'
        arch: 'clang_64'

    - uses: actions/checkout@v3

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the build command line here.
      run: |
        qmake ${{env.SOLUTION_FILE_PATH}}
        make
